=== engarnietemp/EGBank/data/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="accounts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="account" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                        	<xs:element name="accountNumber" type="xs:int"/>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="label" type="xs:string"/>
                            <xs:element name="balance" type="xs:double"/>
                            <xs:element name="client">
                                <xs:complexType>
                                    <xs:sequence>
                                    	<xs:element name="clientNumber" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="firstName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== engarnietemp/EGBank/data/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="accounts.xsd">
    <account>
    	<accountNumber>1</accountNumber>
        <type>CurrentAccount</type>
        <label>Compte courant</label>
        <balance>0.0</balance>
        <client>
        	<clientNumber>1</clientNumber>
            <name>name0</name>
            <firstName>firstName0</firstName>
        </client>
    </account>
    <account>
    	<accountNumber>2</accountNumber>
        <type>SavingsAccount</type>
        <label>Epargne</label>
        <balance>0.0</balance>
        <client>
        <clientNumber>2</clientNumber>
            <name>name0</name>
            <firstName>firstName0</firstName>
        </client>
    </account>
</accounts>
